create table roles (
       id integer generated by default as identity,
        name varchar(20),
        primary key (id)
    );

    create table user_roles (
       user_id bigint not null,
        role_id integer not null,
        primary key (user_id, role_id)
    );

    create table users (
       id bigint generated by default as identity,
        email varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

INSERT into users (username, email, password) VALUES ('admin','test@admin.de','password');

INSERT into roles (name) VALUES ('ROLE_USER');
INSERT into roles (name) VALUES ('ROLE_MODERATOR');
INSERT into roles (name) VALUES ('ROLE_ADMIN');

INSERT into user_roles (user_id,role_id) VALUES (1,1);