
drop table if exists user_roles;
drop table if exists roles;
drop table if exists users;

create table if not exists roles (
       id integer generated by default as identity,
        name varchar(20),
        primary key (id)
    );

    create table if not exists user_roles (
       user_id bigint not null,
        role_id integer not null,
        primary key (user_id, role_id)
    );

    create table if not exists users (
       id bigint generated by default as identity,
        email varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_MODERATOR');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
